### ISSUE TITLE
Include DAP government code into app-layout.js

### ISSUE THREAD

**Issue by deming7h777** [NAL-i5K/NAL-genomics-workspace#13]
@deming7h777 commented on [Tue Oct 16 2018](https://github.com/NAL-i5K/genomics-workspace/issues/246)

Currently, we include the DAP government code into our template

https://github.com/NAL-i5K/NAL-genomics-workspace/blob/5b6e56257be1094e0c70ce8c2e45cda41db26bef/app/templates/app/layout.html#L19

but based on https://github.com/digital-analytics-program/gov-wide-code/issues/65, we can now track this dependency by package.json and include it into app-layout.js generated by django-pipeline

Related links:

https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm
https://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version

---

@hsiaoyi0504 commented on [Tue Oct 16 2018](https://github.com/NAL-i5K/genomics-workspace/issues/246#issuecomment-430288300)

This issue should be opened in [NAL-genomics-workspace](https://github.com/NAL-i5K/NAL-genomics-workspace). Not this one.

**Comment by deming7h777** [comment]
![settings py change](https://user-images.githubusercontent.com/33312760/47101591-7b990f80-d208-11e8-9de6-fefdf51c518b.PNG)

![package](https://user-images.githubusercontent.com/33312760/47101780-05e17380-d209-11e8-9ba2-4f5d5dbd61fa.PNG)

I have changed settings.py  and package.json like these two shotscreen and remove the import in layout.html  but i don't know how to test whether it works or not

**Comment by hsiaoyi0504** [comment]
Push the changes to a new branch and create a new pull request. I can at least do some code review.

**Comment by deming7h777** [comment]
ok ! no problem, but I wonder if I want to test it myself how can I go through

**Comment by hsiaoyi0504** [comment]
As I remember, under debug mode, the static files are not collected by **django-pipeline**. Therefore, you should be able to see the import (I mean the `<script>` tag) when checking the html source code in browser.

**Comment by deming7h777** [comment]
![err packagejson](https://user-images.githubusercontent.com/33312760/47434214-19905b00-d770-11e8-8054-2fd0c03383b2.PNG)
It's the issue i'm dealing with now 
it's fail to install github repo by npm install and most of people who encounter this problem have no idea how to solve it,

**Comment by childers** [comment]
Here is the verbose output form me testing it.

```shell
1183 verbose stack Error: Non-registry package missing package.json: Universal-Federated-Analytics-Min.js@https://github.com/digital-analytics-program/gov-wide-code/archive/master.zip.
1183 verbose stack     at BB.join (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/finalize-manifest.js:162:23)
1183 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
1183 verbose stack     at Holder$5._callFunction (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
1183 verbose stack     at Holder$5.checkFulfillment (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
1183 verbose stack     at Promise.eval (eval at thenCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
1183 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
1183 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
1183 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
1183 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
1183 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
1183 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
1183 verbose stack     at runCallback (timers.js:705:18)
1183 verbose stack     at tryOnImmediate (timers.js:676:5)
1183 verbose stack     at processImmediate (timers.js:658:5)
1184 verbose cwd /Users/cchilders/git-repositories/NAL-genomics-workspace
1185 verbose Darwin 15.6.0
1186 verbose argv "/usr/local/Cellar/node/10.12.0/bin/node" "/usr/local/bin/npm" "install"
1187 verbose node v10.12.0
1188 verbose npm  v6.2.0
1189 error code ENOPACKAGEJSON
1190 error package.json Non-registry package missing package.json: Universal-Federated-Analytics-Min.js@https://github.com/digital-analytics-program/gov-wide-code/archive/master.zip.
1191 error package.json npm can't find a package.json file in your current directory.
1192 verbose exit [ 1, true ]
```
